---
- name: Update apt cache and upgrade all packages
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600

- name: Remove unused dependencies
  ansible.builtin.apt:
    autoremove: yes

- name: Clean apt cache
  ansible.builtin.apt:
    autoclean: yes
